### ISSUE TITLE
The guide does not include the resources that we commonly use for design sprints

### ISSUE THREAD

**Issue by LkeMitchll** [thoughtbot/design-sprint-guide#17]
When we originally worked on the idea of a new guide we created a list of resources that could help people to run a sprint, or a specific exercise. For example a user testing script or a Miro template.

We gathered a few of these resources early on:

[Product Design Sprint Guide Rebuild: Information Architecture | Trello](https://trello.com/b/AzemhufV/product-design-sprint-guide-rebuild-information-architecture)

But they are currently not included as a part of this guide.

**Comment by caro-sotillo** [comment]
WIP - I've found it a bit hard to determine what kind of content has been added already and what hasn't. I found some of the exercises from that Trello board on the current WIP Guide. Not sure if that's because they come from somewhere else 

Example schedules to be added:

- [x] Classic (GV Flavor)
- [x] Classic (thoughtbot Flavor)
- [ ] [Condensed: 3-day](https://trello.com/c/gXMK1i7c/61-condensed-3-day)
- [ ] [Extended: 2 week](https://trello.com/c/PtKjpDaI/62-extended-2-week)
- [ ] [Discovery Sprint](https://trello.com/c/7pDgHCfN/60-discovery-sprint)
- [ ] Brand sprint
- [ ] Lightning Decision Jam

Exercises that need to be added:
- [ ] Planning/Prepare
   - [ ] [Ice breakers and bonding activities](https://trello.com/c/eKUdSa03/66-ice-breakers-and-bonding-activities)
   - [ ] [Resource: Miro Template](https://trello.com/c/hdQAvpmz/28-resource-miro-template)
   - [ ] Resource: Pre-sprint prep email
   - [ ] [Resource: Intro to miro](https://trello.com/c/y1pV5Hzd/50-resource-intro-to-miro)
   - [ ] [Tips](https://trello.com/c/PpnySVZB/71-tips)

- [ ] Understand
   - [ ]
