### ISSUE TITLE
We have no plan for how to launch this guide

### ISSUE THREAD

**Issue by LkeMitchll** [thoughtbot/design-sprint-guide#18]
We currently have no plan on how to launch this guide as part of the thoughtbot website.

Questions include:

- Do we have a thoughtbot Netlify account to deploy this to?
- What should the URL be?
- Who is going actually set it live (I don't have those expertise)
- How should we publicise that?

There may be others...

---

- [ ] Prepare an introductory blog post. (@LkeMitchll)

**Comment by LkeMitchll** [comment]
@cpytel I'm thinking that you might be able to help us with this.

**Comment by cpytel** [comment]
> Do we have a thoughtbot Netlify account to deploy this to?

Yes: https://hub.thoughtbot.com/handbook/business-operations/netlify.md

> Who is going actually set it live

Yes, I can do this.

> What should the URL be?

My proposal from the monthly design meeting was to actually use what we are creating here as the basis for `design.thoughtbot.com`. My meaning is that this repo and this tech stack becomes what design.thoughtbot.com will eventually be. So my suggestion would be to make the url for this be something like

* `design.thoughtbot.com/sprints`
* `design.thoughtbot.com/guide`
* or `design.thoughtbot.com/sprint-guide`

That would preserve the homepage of `design.thoughtbot.com` to eventually become something else. If we want to launch without worrying about what that homepage would be we can make it so that `design.thoughtbot.com` temporarily redirects to `design.thoughtbot.com/sprint-guide`.

If we don't like the idea of taking this repo and making it the start of `design.thoughtbot.com` then I think what we would do instead is bring this live at the existing url `thoughtbot.com/product-design-sprint/guide` or a a new shorter url on thoughtbot.com like `https://thoughtbot.com/design-sprint-guide` which all other urls would link to.

While we're on the topic of urls, I also plan to put redirects in place to ensure we don't break existing urls. So, for example, `thoughtbot.com/product-design-sprint/guide/understand` will redirect to a place in the new guide that makes sense. And `thoughtbot.com/playbook/validation/product-design-sprint/understand` will go away and be replaced with redirect to that same place.

> How should we publicise that?

* Blog post
* The blog post will automatically post to twitter and LinkedIn

We can come up with other ideas to publicize along the way.

**Comment by LkeMitchll** [comment]
> ...or design.thoughtbot.com/sprint-guide
> 
> That would preserve the homepage of design.thoughtbot.com to eventually become something else. If we want to launch without worrying about what that homepage would be we can make it so that design.thoughtbot.com temporarily redirects to design.thoughtbot.com/sprint-guide.

@cpytel I think this is a good plan, Rami was looking into using this repo as the starting point for his work, so we should move forwards with that.

As for launch date I'm wondering if the first Friday of 2023 is a good goal (6th). I think that folks want to work on this as part of Ralphapalooza, Friday is a Disconnect Day, and quite a few people (including me) will be out until January after that. I also don't want to invade your Ralphapalooza time to get this live. So it seems like the 6th would be less stressful?

I can start prepping a blog post.

**Comment by cpytel** [comment]
This project is currently the leading contender for what I'd like to work work on during Ralphapalooza, so you don't need to worry invading my time.

**Comment by cpytel** [comment]
Closing in favor of other, more specific issues, especially #71 and #35.
